# Generated by Django 5.2 on 2025-09-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                (
                    "q_category",
                    models.CharField(max_length=50, verbose_name="사회 / 신체 / 정신"),
                ),
                ("question", models.CharField(max_length=50, verbose_name="질문")),
                ("answer", models.CharField(max_length=50, verbose_name="대답")),
            ],
        ),
        migrations.CreateModel(
            name="OpenAITxt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                (
                    "openai_txt",
                    models.TextField(max_length=20000, verbose_name="openai텍스트"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                ("sex", models.CharField(max_length=50, verbose_name="성별")),
                ("tendency", models.CharField(max_length=50, verbose_name="성향")),
                (
                    "latest_information",
                    models.CharField(max_length=50, verbose_name="최근정보"),
                ),
            ],
        ),
    ]
