# Generated by Django 5.2 on 2025-09-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("s2t", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="M_UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("m_name", models.CharField(max_length=50, verbose_name="지원사_이름")),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                ("sex", models.CharField(max_length=50, verbose_name="성별")),
                ("tendency", models.CharField(max_length=50, verbose_name="성향")),
                (
                    "latest_information",
                    models.CharField(max_length=50, verbose_name="최근정보"),
                ),
            ],
        ),
    ]
